version: '2.1'
services:
  notify-mongo:
    container_name: notify-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - mongodb_vol:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - services-tier

  notify-node:
    container_name: notify-node
    restart: always
    depends_on:
      notify-mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
    env_file:
      - .env

volumes:
  mongodb_vol:

networks:
  services-tier:
